
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import sys
import os
import main_stl
import main_gcode
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title('TotalSTL')
#window.iconbitmap('icon.ico')

window.geometry("900x800")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    427.0,
    41.0,
    472.0,
    801.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    900.0,
    41.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    384.0,
    9.0,
    anchor="nw",
    text="Total_STL\n",
    fill="#000000",
    font=("Inter", 24 * -1)
)

def button_1():
    okno =Tk()
    def exit():
        okno.destroy()
    okno.title('Information')
    ttk.Label(okno, text="TotalSTL").pack()
    ttk.Label(okno, text="version: 0.0.2").pack()
    ttk.Label(okno, text="Author: Piotr Pawlik").pack()
    ttk.Label(okno, text="Jest to oprogramowanie pozwalajace na wyswietlanie plikow .STL, zarządzanie nimi i przeglądanie plikow .GCODE dla drukarek 3D").pack()
    ttk.Button(okno, text="EXIT", command=exit).pack()

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_1,
    relief="flat"
)
button_1.place(
    x=744.0,
    y=7.0,
    width=80.0,
    height=25.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=main_stl.STL_view,
    relief="flat"
)
button_2.place(
    x=7.0,
    y=8.0,
    width=62.039268493652344,
    height=25.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=main_gcode.GCODE,
    relief="flat"
)
button_3.place(
    x=79.0,
    y=8.0,
    width=81.0,
    height=25.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=sys.exit,
    relief="flat"
)
button_4.place(
    x=827.0,
    y=7.0,
    width=53.0,
    height=25.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=432.0,
    y=65.0,
    width=35.0,
    height=52.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=432.0,
    y=148.0,
    width=35.0,
    height=52.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=432.0,
    y=224.0,
    width=35.0,
    height=52.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=432.0,
    y=300.0,
    width=35.0,
    height=52.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=432.0,
    y=376.0,
    width=35.0,
    height=52.0
)

canvas.create_rectangle(
    0.0,
    51.0,
    416.0,
    800.0,
    fill="#AFADAD",
    outline="")

canvas.create_rectangle(
    484.0,
    52.0,
    900.0,
    801.0,
    fill="#AFADAD",
    outline="")
window.resizable(False, False)
window.mainloop()
