
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import sys
import os
import main_stl
import main_gcode
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title('TotalSTL')

window.geometry("900x480")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 480,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    40.0,
    45.0,
    480.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    900.0,
    41.0,
    fill="#D9D9D9",
    outline="")

def button_1():
    okno =Tk()
    def exit():
        okno.destroy()
    okno.title('Information')
    ttk.Label(okno, text="TotalSTL").pack()
    ttk.Label(okno, text="version: 0.0.2").pack()
    ttk.Label(okno, text="Author: Piotr Pawlik").pack()
    ttk.Label(okno, text="Jest to oprogramowanie pozwalajace na wyswietlanie plikow .STL, zarządzanie nimi i przeglądanie/edytowanie plikow .GCODE dla drukarek 3D").pack()
    ttk.Button(okno, text="EXIT", command=exit).pack()

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button_1,
    relief="flat"
)
button_1.place(
    x=744.0,
    y=7.0,
    width=80.0,
    height=25.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=main_stl.STL_view,
    relief="flat"
)
button_2.place(
    x=7.0,
    y=8.0,
    width=62.039268493652344,
    height=25.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=main_gcode.GCODE,
    relief="flat"
)
button_3.place(
    x=79.0,
    y=8.0,
    width=81.0,
    height=25.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=sys.exit,
    relief="flat"
)
button_4.place(
    x=827.0,
    y=7.0,
    width=53.0,
    height=25.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=4.0,
    y=60.0,
    width=35.0,
    height=52.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=4.0,
    y=131.0,
    width=35.0,
    height=52.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=4.0,
    y=202.0,
    width=35.0,
    height=52.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=4.0,
    y=273.0,
    width=35.0,
    height=52.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=5.0,
    y=344.0,
    width=35.0,
    height=52.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=0.0,
    y=415.0,
    width=45.0,
    height=57.0
)

canvas.create_rectangle(
    855.0,
    41.0,
    900.0,
    480.0,
    fill="#D9D9D9",
    outline="")

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=859.0,
    y=61.0,
    width=35.0,
    height=52.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=859.0,
    y=132.0,
    width=35.0,
    height=52.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=859.0,
    y=203.0,
    width=35.0,
    height=52.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=859.0,
    y=274.0,
    width=35.0,
    height=52.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_15 clicked"),
    relief="flat"
)
button_15.place(
    x=860.0,
    y=345.0,
    width=35.0,
    height=52.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_16 clicked"),
    relief="flat"
)
button_16.place(
    x=855.0,
    y=416.0,
    width=45.0,
    height=57.0
)

canvas.create_rectangle(
    45.0,
    41.0,
    435.0,
    480.0,
    fill="#AFADAD",
    outline="")

canvas.create_rectangle(
    465.0,
    41.0,
    855.0,
    480.0,
    fill="#AFADAD",
    outline="")

canvas.create_rectangle(
    435.0,
    41.0,
    465.0,
    480.0,
    fill="#A40A0A",
    outline="")

canvas.create_rectangle(
    53.0,
    50.0,
    427.0,
    472.0,
    fill="#A9E6AF",
    outline="")

canvas.create_rectangle(
    473.0,
    50.0,
    847.0,
    472.0,
    fill="#A9E7AF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    20.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
